/*
 * This file is part of FlyCat.
 *
 * FlyCat is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 *
 * Copyright (c)  YumeYucca 2025 - Present
 * Based on YumeBox by YumeYucca
 *
 */

package com.suanran.dreambox.runtime.service.profile

import android.content.Context
import androidx.work.Constraints
import androidx.work.CoroutineWorker
import androidx.work.ExistingPeriodicWorkPolicy
import androidx.work.NetworkType
import androidx.work.PeriodicWorkRequestBuilder
import androidx.work.WorkerParameters
import androidx.work.WorkManager
import com.suanran.dreambox.core.Clash
import com.suanran.dreambox.core.importedDir
import com.suanran.dreambox.core.model.FetchStatus
import com.suanran.dreambox.core.model.profile.Imported
import com.suanran.dreambox.core.model.profile.Profile
import com.suanran.dreambox.core.util.SingBoxConverter
import com.suanran.dreambox.runtime.api.remote.IFetchObserver
import com.suanran.dreambox.runtime.service.config.ServiceStore
import com.suanran.dreambox.runtime.service.records.ImportedDao
import com.suanran.dreambox.runtime.service.records.SelectionDao
import com.suanran.dreambox.runtime.service.util.Log
import com.suanran.dreambox.runtime.service.util.sendProfileChanged
import java.io.File
import java.util.UUID
import java.util.concurrent.TimeUnit
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.NonCancellable
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext
import timber.log.Timber

object ProfileProcessor {
    private val profileLock = Mutex()
    private val processLock = Mutex()

    private data class SubscriptionInfo(
        val upload: Long? = null,
        val download: Long? = null,
        val total: Long? = null,
        val expire: Long? = null,
        val title: String? = null,
        val filename: String? = null,
        val updateInterval: Long? = null,
    )

    private data class UpdateSnapshot(
        val imported: Imported,
        val hasCommittedConfig: Boolean,
    )

    private fun FetchStatus.toSubscriptionInfo(): SubscriptionInfo? {
        if (action != FetchStatus.Action.SubscriptionInfo) return null
        return SubscriptionInfo(
            upload = subUpload,
            download = subDownload,
            total = subTotal,
            expire = subExpire,
            title = subTitle,
            filename = subFilename,
            updateInterval = subUpdateInterval,
        )
    }

    private fun resolveSubscriptionName(
        snapshotName: String,
        snapshotSource: String,
        subInfo: SubscriptionInfo?,
    ): String {
        if (!ProfileNameUtils.isAutoGeneratedProfileName(snapshotName)) return snapshotName

        val headerTitle = subInfo?.title?.takeIf { it.isNotBlank() }
        val filename = subInfo?.filename?.substringBeforeLast(".")?.takeIf { it.isNotBlank() }
        val sourceName = ProfileNameUtils.extractSourceBaseName(snapshotSource)

        if (headerTitle != null) return headerTitle
        if (filename != null) return filename
        if (sourceName != null) return sourceName
        return snapshotName
    }

    @Suppress("TooGenericExceptionCaught")
    suspend fun update(context: Context, uuid: UUID, callback: IFetchObserver?) {
        withContext(Dispatchers.IO + NonCancellable) {
            processLock.withLock {
                val targetDir = context.importedDir.resolve(uuid.toString())
                val stagingDir =
                    context.noBackupFilesDir.resolve("profile-staging").resolve(uuid.toString())
                val snapshot = profileLock.withLock {
                    val imported =
                        ImportedDao.queryByUUID(uuid)
                            ?: throw IllegalArgumentException("profile $uuid not found")

                    stagingDir.deleteRecursively()
                    stagingDir.mkdirs()

                    if (targetDir.exists()) {
                        targetDir.copyRecursively(stagingDir, overwrite = true)
                    }

                    UpdateSnapshot(
                        imported = imported,
                        // Sentinel for "this profile has already committed a config", used below to decide whether a failed update may roll back (delete) the profile.
                        // The source profile file is config.yaml (written by fetchAndValid on a successful fetch); runtime.yaml is no longer produced by any path, so it can never serve as this sentinel.
                        hasCommittedConfig = targetDir.resolve("config.yaml").isFile,
                    )
                }

                var cb = callback
                var subInfo: SubscriptionInfo? = null

                try {
                    Clash.setAgeSecretKey(snapshot.imported.ageSecretKey)

                    // 对于本地文件配置文件，配置已被调用者复制到 stagingDir 中。
                    // 跳过 fetch (force=false) 并让本机代码直接验证现有的 config.yaml。
                    val isLocalFile = snapshot.imported.type == Profile.Type.File && snapshot.imported.source.startsWith("content://")

                    suspend fun doFetch(force: Boolean) {
                        Clash.fetchAndValid(stagingDir, snapshot.imported.source, force) {
                                val fetchedSubInfo = it.toSubscriptionInfo()
                                if (fetchedSubInfo != null) {
                                    subInfo = fetchedSubInfo
                                    return@fetchAndValid
                                }

                                try {
                                    cb?.updateStatus(it)
                                } catch (error: Exception) {
                                    // fault barrier: the observer may live across a binder; reporting
                                    // failures must not abort the profile fetch itself.
                                    cb = null
                                    Timber.w(error, "Report fetch status: %s", error.message)
                                }
                            }
                            .await()
                    }

                    try {
                        doFetch(!isLocalFile)
                    } catch (fetchError: Exception) {
                        // DreamBox: 订阅/文件返回的可能是 sing-box JSON（含 outbounds），mihomo 原生无法解析。
                        // 尝试原地转换为 Mihomo proxies YAML 后再校验一次；转换失败则抛出原始错误。
                        if (tryConvertSingBox(stagingDir)) {
                            Timber.i("SingBoxConverter: retrying validation after conversion")
                            doFetch(false)
                        } else {
                            throw fetchError
                        }
                    }

                    profileLock.withLock {
                        if (ImportedDao.exists(snapshot.imported.uuid)) {
                            // 原子交换：将旧文件重命名为备份，将暂存文件重命名为目标文件。
                            // 如果进程在操作过程中终止，启动恢复将还原 .bak 文件。
                            val backupDir = context.importedDir.resolve("${uuid}.bak")
                            backupDir.deleteRecursively()
                            if (targetDir.exists()) {
                                moveDirectory(targetDir, backupDir)
                            }
                            moveDirectory(stagingDir, targetDir)
                            backupDir.deleteRecursively()

                            val finalName =
                                if (snapshot.imported.type == Profile.Type.Url) {
                                    resolveSubscriptionName(
                                        snapshot.imported.name,
                                        snapshot.imported.source,
                                        subInfo,
                                    )
                                } else {
                                    snapshot.imported.name
                                }

                            val updated =
                                Imported(
                                    snapshot.imported.uuid,
                                    finalName,
                                    snapshot.imported.type,
                                    snapshot.imported.source,
                                    subInfo?.updateInterval ?: snapshot.imported.interval,
                                    subInfo?.upload ?: snapshot.imported.upload,
                                    subInfo?.download ?: snapshot.imported.download,
                                    subInfo?.total ?: snapshot.imported.total,
                                    subInfo?.expire ?: snapshot.imported.expire,
                                    snapshot.imported.createdAt,
                                    ageSecretKey = snapshot.imported.ageSecretKey,
                                    updatedAt = System.currentTimeMillis(),
                                )
                            ImportedDao.update(updated)
                            AutoUpdate.reschedule(context)
                            context.sendProfileChanged(snapshot.imported.uuid)
                        }
                    }
                } catch (error: Exception) {
                    // fault barrier: core fetch runs through the JNI bridge; roll back the staged update atomically, then rethrow (with a friendlier message for age errors).
                    profileLock.withLock {
                        if (
                            !snapshot.hasCommittedConfig &&
                                ImportedDao.exists(snapshot.imported.uuid)
                        ) {
                            ImportedDao.remove(snapshot.imported.uuid)
                            SelectionDao.clear(snapshot.imported.uuid)
                            targetDir.deleteRecursively()
                            context.sendProfileChanged(snapshot.imported.uuid)
                        } else if (ImportedDao.exists(snapshot.imported.uuid)) {
                            // Restore from .bak if atomic swap left orphaned backup
                            val backupDir =
                                context.importedDir.resolve("${uuid}.bak")
                            if (backupDir.exists() && !targetDir.exists()) {
                                moveDirectory(backupDir, targetDir)
                            }
                            backupDir.deleteRecursively()
                        }
                    }
                    // 为Age解密失败提供更加用户友好型的错误消息
                    val errorMessage = error.message ?: ""
                    if (
                        errorMessage.contains("no identities specified") ||
                            errorMessage.contains("decrypt config error")
                    ) {
                        throw IllegalArgumentException(
                            "This config is encrypted with age. Please provide the age secret key when importing the config.",
                            error,
                        )
                    } else {
                        throw error
                    }
                } finally {
                    stagingDir.deleteRecursively()
                }
            }
        }
    }

    // 将[源文件]移动到[目标位置]，当[File.renameTo]静默失败时（例如在某些Android设备跨文件系统挂载点操作时），回退使用复制+删除的方式。
    private fun moveDirectory(source: File, target: File) {
        if (source.renameTo(target)) return
        // "renameTo 返回 false — 则回退到递归复制"
        target.deleteRecursively()
        source.copyRecursively(target, overwrite = true)
        source.deleteRecursively()
    }

    suspend fun delete(context: Context, uuid: UUID) {
        withContext(Dispatchers.IO + NonCancellable) {
            profileLock.withLock {
                ImportedDao.remove(uuid)
                SelectionDao.clear(uuid)

                val imported = context.importedDir.resolve(uuid.toString())
                imported.deleteRecursively()

                context.sendProfileChanged(uuid)
            }
        }
    }

    suspend fun active(context: Context, uuid: UUID) {
        withContext(Dispatchers.IO + NonCancellable) {
            profileLock.withLock {
                if (!ImportedDao.exists(uuid)) {
                    throw IllegalArgumentException("profile $uuid is not available")
                }
                val store = ServiceStore()
                store.activeProfile = uuid
                context.sendProfileChanged(uuid)
            }
        }
    }

    /**
     * 基于 WorkManager 的订阅自动更新：全部订阅共用单个周期任务（周期 = 各订阅 interval 的最小值），每次运行按锚点批量更新到期订阅，任务数不随订阅数增长。
     */
    object AutoUpdate {
        const val MIN_INTERVAL_SECONDS = 30 * 60L
        /** 合批前瞻窗口：到期时间落在窗口内的订阅并入本批（最多提前一个窗口执行）。 */
        const val BATCH_WINDOW_SECONDS = 15 * 60L
        private const val TAG = "ProfileAutoUpdate"
        private const val WORK_NAME = "profile_auto_update_all"
        private const val WORK_TAG = "profile_update_all"
        private const val LEGACY_WORK_TAG = "profile_update"
        /** 在应用启动时同步调度；不重锚定周期，避免频繁启动推迟更新。 */
        fun scheduleAll(context: Context) {
            WorkManager.getInstance(context).cancelAllWorkByTag(LEGACY_WORK_TAG)
            reschedule(context, reanchor = false)
        }
        /** 订阅集合/间隔变化或更新完成后调用；[reanchor] 为 true 时从当前时刻重新起算周期。 */
        fun reschedule(context: Context, reanchor: Boolean = true) {
            val profiles = ImportedDao.queryAll().filter { it.type == Profile.Type.Url && it.interval >= MIN_INTERVAL_SECONDS }
            val workManager = WorkManager.getInstance(context)
            if (profiles.isEmpty()) {
                workManager.cancelUniqueWork(WORK_NAME)
                Timber.tag(TAG).i("Cancelled auto-update (no eligible profiles)")
                return
            }
            val periodSeconds = profiles.minOf { it.interval }
            val request = PeriodicWorkRequestBuilder<ProfileAutoUpdateWorker>(
                    repeatInterval = periodSeconds,
                    repeatIntervalTimeUnit = TimeUnit.SECONDS,
                ).setConstraints(Constraints.Builder().setRequiredNetworkType(NetworkType.CONNECTED).build()).addTag(WORK_TAG).build()
            val policy =
                if (reanchor) ExistingPeriodicWorkPolicy.UPDATE else ExistingPeriodicWorkPolicy.KEEP
            workManager.enqueueUniquePeriodicWork(WORK_NAME, policy, request)
            Timber.tag(TAG).i("Scheduled auto-update for ${profiles.size} profiles every ${periodSeconds}s ($policy)")
        }
    }
}

/**
 * DreamBox: best-effort sing-box JSON -> Mihomo conversion.
 *
 * When a subscription (or imported file) returns sing-box JSON instead of a
 * Mihomo/Clash YAML, the native fetchAndValid validation fails. This rewrites
 * [stagingDir]/config.yaml in place with the converted `proxies:` YAML and
 * returns true so the caller can retry validation. Never throws.
 */
private fun tryConvertSingBox(stagingDir: File): Boolean =
    runCatching {
        val configFile = stagingDir.resolve("config.yaml")
        if (!configFile.isFile) return false
        val text = configFile.readText()
        if (!SingBoxConverter.isSingBoxConfig(text)) return false
        val result = SingBoxConverter.convert(text) ?: return false
        if (result.converted <= 0) return false
        configFile.writeText(result.yaml)
        Timber.i(
            "SingBoxConverter: converted %d proxies (%d skipped) for profile update",
            result.converted,
            result.skipped,
        )
        result.warnings.take(5).forEach { Timber.w("SingBoxConverter: %s", it) }
        true
    }.getOrElse {
        Timber.w(it, "SingBoxConverter: conversion failed")
        false
    }

/**
 * 周期性批量更新到期订阅。由 [ProfileProcessor.AutoUpdate] 以单任务统一调度，每次运行更新所有距上次更新已达自身 `interval` 的 URL 订阅。
 */
class ProfileAutoUpdateWorker(
    appContext: Context,
    params: WorkerParameters,
) : CoroutineWorker(appContext, params) {
    override suspend fun doWork(): Result {
        val nowMs = System.currentTimeMillis()
        val windowMs = ProfileProcessor.AutoUpdate.BATCH_WINDOW_SECONDS * 1000
        val batch = ImportedDao.queryAll()
            .filter { it.type == Profile.Type.Url && it.interval >= ProfileProcessor.AutoUpdate.MIN_INTERVAL_SECONDS }
            .map { it to anchorOf(it) + it.interval * 1000 }
            .filter { (_, dueAt) -> dueAt <= nowMs + windowMs }
            .sortedBy { (_, dueAt) -> dueAt }
            .map { (imported, _) -> imported }
        if (batch.isEmpty()) return Result.success()
        // 激活订阅的更新会触发配置重载（瞬断），置队尾让其余下载先完成。
        val activeUuid = ServiceStore().activeProfile
        val (others, active) = batch.partition { it.uuid != activeUuid }
        val queue = others + active
        Timber.tag(TAG).i("Auto-update batch: ${queue.size} due, activeLast=${active.isNotEmpty()}")
        var failures = 0
        for (imported in queue) {
            try {
                Timber.tag(TAG).i("Auto-updating profile: ${imported.name} (${imported.uuid})")
                ProfileProcessor.update(applicationContext, imported.uuid, null)
                Timber.tag(TAG).i("Auto-update complete: ${imported.name}")
            } catch (error: Exception) {
                if (error is CancellationException) throw error
                failures++
                Timber.tag(TAG).w(error, "Auto-update failed for profile ${imported.uuid}")
            }
        }
        return if (failures > 0) Result.retry() else Result.success()
    }
    // 历史数据 updatedAt=0 时以创建时间兜底，避免刚导入的订阅立即触发一次冗余更新。
    private fun anchorOf(imported: Imported): Long = maxOf(imported.updatedAt, imported.createdAt)
    companion object {
        private const val TAG = "ProfileAutoUpdate"
    }
}
