/*
 * This file is part of FlyCat.
 *
 * FlyCat is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 *
 * Copyright (c)  YumeYucca 2025 - Present
 * Based on YumeBox by YumeYucca
 *
 */

package com.suanran.dreambox.runtime.service.profile

import java.net.URLDecoder
import java.nio.charset.StandardCharsets
import java.util.Locale

internal object ProfileNameUtils {
    private val autoNameSet = setOf("newprofile", "remotefile", "新配置", "新配置文件")

    fun isAutoGeneratedProfileName(name: String): Boolean {
        val normalized = name.trim()
        if (normalized.isBlank()) return true
        if (normalized.startsWith("temp_", ignoreCase = true)) return true

        val lowered =
            normalized
                .lowercase(Locale.getDefault())
                .replace(" ", "")
                .replace("_", "")
                .replace("-", "")

        return lowered in autoNameSet
    }

    fun extractSourceBaseName(source: String): String? =
        runCatching {
                source
                    .substringBefore('?')
                    .substringBefore('#')
                    .substringAfterLast('/')
                    .substringBeforeLast('.')
                    .let { URLDecoder.decode(it, StandardCharsets.UTF_8.name()) }
                    .trim()
                    .takeIf { it.isNotBlank() }
            }
            .getOrNull()

    fun resolveDisplayName(name: String, source: String): String {
        if (!isAutoGeneratedProfileName(name)) return name
        return extractSourceBaseName(source) ?: name
    }
}
