"""Mihomo core version identity handling."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
import re

from .command import execute_command
from .config import ProjectConfig


@dataclass
class CoreVersionStamp:
    branch: str
    commit: str
    display_version: str
    git_version_arg: str
    build_time: str

    def to_properties_text(self) -> str:
        return (
            "# Generated by scripts/native-build.py — do not edit.\n"
            f"core.branch={self.branch}\n"
            f"core.commit={self.commit}\n"
            f"core.displayVersion={self.display_version}\n"
            f"core.gitVersion={self.git_version_arg}\n"
            f"core.buildTime={self.build_time}\n"
        )


def run_git(repo_dir: Path, args: list[str]) -> str | None:
    if not repo_dir.is_dir() or not (repo_dir / ".git").exists():
        return None
    result = execute_command(
        ["git", "-C", str(repo_dir), *args],
        print_stdout=False,
        print_stderr=False,
        stderr_is_error=False,
    )
    if not result.success:
        return None
    value = result.output.strip().splitlines()
    return value[0].strip() if value and value[0].strip() else None


def resolve_core_version_stamp(config: ProjectConfig, project_root: Path) -> CoreVersionStamp:
    configured_branch = config.get_string("external.mihomo.branch", "Alpha") or "Alpha"
    suffix = config.get_string("external.mihomo.suffix")
    include_timestamp = config.get_bool("external.mihomo.includeTimestamp", False)
    repo_dir = project_root / config.get_string("external.mihomo.dir", "lib/mihomo/mihomo")
    commit = run_git(repo_dir, ["rev-parse", "--short=8", "HEAD"])
    if not commit or not re.fullmatch(r"[0-9a-fA-F]{4,40}", commit):
        commit = "unknown"
    git_branch = run_git(repo_dir, ["rev-parse", "--abbrev-ref", "HEAD"])
    if git_branch == "HEAD":
        git_branch = None
    branch_base = configured_branch or git_branch or "mihomo"
    branch = branch_base + suffix
    build_time = datetime.now().strftime("%Y%m%d%H%M") if include_timestamp else "local"
    display_version = f"{branch}-{commit}"
    git_version_arg = f"{branch.replace('_', '-')}_{commit}_{build_time}"
    return CoreVersionStamp(branch, commit, display_version, git_version_arg, build_time)


def write_core_version_stamp(stamp: CoreVersionStamp, abis: list[str], project_root: Path) -> None:
    text = stamp.to_properties_text()
    generated = project_root / "build/generated/core-version.properties"
    generated.parent.mkdir(parents=True, exist_ok=True)
    generated.write_text(text, encoding="utf-8")
    print(f"[GoCore] Stamped core version: {stamp.display_version} -> {generated}")
    for abi in abis:
        destination = project_root / "jniLibs" / abi / "core-version.properties"
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(text, encoding="utf-8")

