//! Key order used when serializing the compiled config back to YAML.
//!
//! Keys listed here are emitted first, in this order; every other key follows in the map's own (lexicographic) order.

use crate::model::SchemaId;

pub const ROOT_ORDER: &[&str] = &[
    "mode",
    "log-level",
    "ipv6",
    "find-process-mode",
    "keep-alive-interval",
    "keep-alive-idle",
    "unified-delay",
    "tcp-concurrent",
    "geodata-mode",
    "allow-lan",
    "bind-address",
    "lan-allowed-ips",
    "lan-disallowed-ips",
    "authentication",
    "skip-auth-prefixes",
    "external-controller",
    "external-controller-tls",
    "external-doh-server",
    "secret",
    "external-controller-cors",
    "profile",
    "interface-name",
    "routing-mark",
    "geosite-matcher",
    "global-client-fingerprint",
    "geo-auto-update",
    "geo-update-interval",
    "geox-url",
    "dns",
    "clash-for-android",
    "hosts",
    "sniffer",
    "port",
    "socks-port",
    "mixed-port",
    "redir-port",
    "tun",
    "proxies",
    "proxy-providers",
    "proxy-groups",
    "rules",
    "rule-providers",
    "sub-rules",
];
pub const DNS_ORDER: &[&str] = &[
    "enable",
    "cache-algorithm",
    "prefer-h3",
    "listen",
    "ipv6",
    "use-hosts",
    "use-system-hosts",
    "respect-rules",
    "enhanced-mode",
    "fake-ip-range",
    "fake-ip-range6",
    "fake-ip-filter-mode",
    "fake-ip-ttl",
    "ipv6-timeout",
    "cache-max-size",
    "direct-nameserver-follow-policy",
    "default-nameserver",
    "nameserver",
    "fallback",
    "proxy-server-nameserver",
    "direct-nameserver",
    "nameserver-policy",
    "proxy-server-nameserver-policy",
    "fake-ip-filter",
    "fallback-filter",
];
pub const DNS_FALLBACK_FILTER_ORDER: &[&str] =
    &["geoip", "geoip-code", "domain", "ipcidr", "geosite"];
pub const SNIFFER_ORDER: &[&str] = &[
    "enable",
    "force-dns-mapping",
    "parse-pure-ip",
    "override-destination",
    "sniff",
    "force-domain",
    "skip-domain",
    "skip-src-address",
    "skip-dst-address",
];
pub const SNIFF_ORDER: &[&str] = &["HTTP", "TLS", "QUIC"];
pub const PROTOCOL_ORDER: &[&str] = &["ports", "override-destination"];
pub const TUN_ORDER: &[&str] = &[
    "enable",
    "stack",
    "auto-route",
    "auto-redirect",
    "auto-detect-interface",
    "strict-route",
    "endpoint-independent-nat",
    "mtu",
    "gso",
    "gso-max-size",
    "disable-icmp-forwarding",
    "dns-hijack",
    "route-address",
    "route-exclude-address",
    "include-package",
    "exclude-package",
];
pub const EXTERNAL_CONTROLLER_CORS_ORDER: &[&str] = &["allow-origins", "allow-private-network"];
pub const PROFILE_ORDER: &[&str] = &["store-selected", "store-fake-ip"];
pub const GEOX_URL_ORDER: &[&str] = &["geoip", "mmdb", "geosite"];
pub const APP_ORDER: &[&str] = &["append-system-dns"];
pub const PROXY_ITEM_ORDER: &[&str] = &[
    "name",
    "type",
    "server",
    "port",
    "ip-version",
    "udp",
    "interface-name",
    "routing-mark",
    "tfo",
    "mptcp",
    "dialer-proxy",
];
pub const PROXY_GROUP_ITEM_ORDER: &[&str] = &[
    "name",
    "type",
    "proxies",
    "use",
    "url",
    "interval",
    "lazy",
    "timeout",
    "max-failed-times",
    "disable-udp",
    "interface-name",
    "routing-mark",
    "include-all",
    "include-all-proxies",
    "include-all-providers",
    "filter",
    "exclude-filter",
    "exclude-type",
    "expected-status",
    "hidden",
    "icon",
];
pub const PROVIDER_ITEM_ORDER: &[&str] = &[
    "type",
    "url",
    "path",
    "behavior",
    "interval",
    "format",
    "proxy",
    "filter",
    "exclude-filter",
    "exclude-type",
    "size-limit",
    "health-check",
];

pub fn ordered_keys(schema: SchemaId) -> &'static [&'static str] {
    match schema {
        SchemaId::Root => ROOT_ORDER,
        SchemaId::Dns => DNS_ORDER,
        SchemaId::DnsFallbackFilter => DNS_FALLBACK_FILTER_ORDER,
        SchemaId::Sniffer => SNIFFER_ORDER,
        SchemaId::Sniff => SNIFF_ORDER,
        SchemaId::Protocol => PROTOCOL_ORDER,
        SchemaId::Tun => TUN_ORDER,
        SchemaId::ExternalControllerCors => EXTERNAL_CONTROLLER_CORS_ORDER,
        SchemaId::Profile => PROFILE_ORDER,
        SchemaId::GeoxUrl => GEOX_URL_ORDER,
        SchemaId::App => APP_ORDER,
        SchemaId::ProxyItem => PROXY_ITEM_ORDER,
        SchemaId::ProxyGroupItem => PROXY_GROUP_ITEM_ORDER,
        SchemaId::ProviderItem => PROVIDER_ITEM_ORDER,
    }
}
